#!/command/with-contenv bash

source /assets/functions/00-container
# shellcheck disable=SC2034
PROCESS_NAME="mariadb"

check_container_initialized
check_service_initialized init
liftoff

if [ -n "${MYSQLD_ARGS}" ]; then start_string="with extra arguments '${MYSQLD_ARGS}'" ; fi
print_start "Starting MariaDB ${MARIADB_VERSION} ${start_string}"
silent exec s6-setuidgid mariadb \
                                    /usr/bin/mysqld \
                                                    --console \
                                                    --defaults-file="${CONFIG_PATH}"/"${CONFIG_FILE}" \
                                                    --user=mariadb \
                                                    --skip-name-resolve ${MYSQLD_ARGS}