#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-init-mariadb ]
do
  sleep 1
done

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

if [ ! -f /tmp/state/10-mariadb ]; then
    mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-mariadb
fi

echo "** [mariadb] Starting MariaDB" $MARIADB_VERSION
exec /usr/bin/mysqld --defaults-file=/etc/mysql/my.cnf --user=mariadb --console