#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="mariadb"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting MariaDB ${MARIADB_VERSION}"
silent exec /usr/bin/mysqld --defaults-file=/etc/mysql/my.cnf --user=mariadb --console --skip-name-resolve