#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="mariadb"
check_initialized
liftoff

print_info "Starting MariaDB ${MARIADB_VERSION}"
silent exec /usr/bin/mysqld --defaults-file=/etc/mysql/my.cnf --user=mariadb --console --skip-name-resolve