#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
# shellcheck disable=SC2034
PROCESS_NAME="mariadb"

bootstrap_filesystem
bootstrap_variables
configure_mariadb
print_notice "Initializing MariaDB - Please wait.."
initialize_mariadb
create_databases
configure_monitoring

liftoff
