#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
# shellcheck disable=SC2034
PROCESS_NAME="mariadb-backup"

### Enable or disable the database backup script
if var_false "${DB_BACKUP}" ; then
    print_notice "Disabling scheduled backups"
    service_stop 20-mariadb-backup
fi

liftoff
