#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="mariadb-backup"

DB_BACKUP=${DB_BACKUP="FALSE"}

### Enable or Disable the DB Backup Script
if [ "$DB_BACKUP" != "TRUE" ] || [ "$DB_BACKUP" != "true" ]; then
    print_notice "Disabling Scheduled Backups"
    service_stop 20-mariadb-backup
fi

liftoff
