services:
  example-db:
    image: docker.io/nfrastack/mariadb:11.8
    stop_grace_period: 3m
    container_name: example-db
    volumes:
      #- ./config:/config
      - ./db:/data
      - ./logs:/logs
     # - ./restore:/restore
    environment:
      - TIMEZONE=America/Vancouver

      - ROOT_PASS=rootpassword

      #- DB_NAME=database
      #- DB_USER=user
      #- DB_PASS=password

      ### OR
      - DB01_NAME=database_one
      - DB01_USER=database_userone
      - DB01_PASS=password
      #- DB01_RESTORE_FILE=/restore/mariadb.sql.zst
      #- DB01_RESTORE_MODE=init
      - DB02_NAME=database_two
      - DB02_USER=database_usertwo
      - DB02_PASS=password
      - DB03_NAME=database_three
      - DB03_USER=database_userthree
      - DB03_PASS=password

    networks:
      - services
    restart: always

networks:
  services:
    external: true

