#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/20-mariadb-backup
source /assets/functions/20-mariadb-backup
PROCESS_NAME="db-backup"

backup_bootstrap_variables

if [ "${DB_BACKUP_MODE,,}" = "manual" ] || [ "${1,,}" = "manual" ] || [ "${1,,}" = "now" ]; then
    DB_BACKUP_DUMP_BEGIN=+0
    manual=TRUE
    print_debug "Detected Manual Mode"
else
    sleep 5
    current_time=$(date +"%s")
    today=$(date +"%Y%m%d")

    if [[ $DB_BACKUP_DUMP_BEGIN =~ ^\+(.*)$ ]]; then
        waittime=$(( ${BASH_REMATCH[1]} * 60 ))
        target_time=$(($current_time + $waittime))
    else
        target_time=$(date --date="${today}${DB_BACKUP_DUMP_BEGIN}" +"%s")
        if [[ "$target_time" < "$current_time" ]]; then
            target_time=$(($target_time + 24*60*60))
        fi
        waittime=$(($target_time - $current_time))
    fi
    print_debug "Wait Time: ${waittime} Target time: ${target_time} Current Time: ${current_time}"
    print_info "Next Backup at $(date -d @${target_time} +"%Y-%m-%d %T %Z")"
    sleep $waittime
fi

while true; do
    mkdir -p "${DB_BACKUP_TEMP_LOCATION}"
    backup_start_time=$(date +"%s")
    print_debug "Backup routines started time: $(date +'%Y-%m-%d %T %Z')"
    case "${dbtype,,}" in
        "mysql" )
            backup_check_availability
            backup_mysql
        ;;
        esac

    backup_finish_time=$(date +"%s")
    backup_total_time=$(echo $((backup_finish_time-backup_start_time)))
    if [ -z "$master_exit_code" ] ; then master_exit_code="0" ; fi
    print_info "Backup routines finish time: $(date -d @${backup_finish_time} +"%Y-%m-%d %T %Z") with overall exit code ${master_exit_code}"
    print_notice "Backup routines time taken: $(echo ${backup_total_time} | awk '{printf "Hours: %d Minutes: %02d Seconds: %02d", $1/3600, ($1/60)%60, $1%60}')"

    backup_cleanup_old_data

    if var_true "${manual}" ; then
        print_debug "Exiting due to manual mode"
        exit ${master_exit_code};
    else
        print_notice "Sleeping for another $(($DB_BACKUP_DUMP_FREQ*60-backup_total_time)) seconds. Waking up at $(date -d@"$(( $(date +%s)+$(($DB_BACKUP_DUMP_FREQ*60-backup_total_time))))" +"%Y-%m-%d %T %Z") "
        sleep $(($DB_BACKUP_DUMP_FREQ*60-backup_total_time))
    fi
done
